In [4]:
import pandas as pd

In [10]:
df=pd.read_csv('/content/ecoli_chemotaxis_simulation.csv')

In [11]:
df.head()

,bacterium_id,time_s,x_um,y_um,heading_rad,speed_um_s,motor_state,is_tumble,tumble_angle_rad,attractant_conc_uM,repellent_conc_uM,net_signal,signal_delta,tumble_probability,energy_level,dist_to_attractant_center_um,dist_to_repellent_center_um
0,0,0.0,38.418,89.097,4.5993,19.532,CCW,0,0.0000,397.0274,46.9390,373.5579,0.0000,0.1000,99.8,40.777,42.566
1,0,0.1,38.418,89.097,0.9652,0.000,CW,1,2.3671,397.0274,46.9390,373.5579,23.4903,0.0889,99.1,40.777,42.566
2,0,0.2,39.333,90.475,0.9652,18.838,CCW,0,0.0000,377.8229,48.7878,353.4289,0.0000,0.1000,98.9,41.857,41.995
3,0,0.3,39.849,91.798,0.9652,18.152,CCW,0,0.0000,357.7704,49.2668,333.1370,-20.1290,0.1000,98.7,43.013,41.849
4,0,0.4,40.716,93.161,0.9652,19.144,CCW,0,0.0000,338.6360,50.6601,313.3059,-20.2919,0.1000,98.5,44.149,41.430

In [13]:
df.tail()

,bacterium_id,time_s,x_um,y_um,heading_rad,speed_um_s,motor_state,is_tumble,tumble_angle_rad,attractant_conc_uM,repellent_conc_uM,net_signal,signal_delta,tumble_probability,energy_level,dist_to_attractant_center_um,dist_to_repellent_center_um
29995,499,5.5,22.425,56.680,5.2888,21.035,CCW,0,0.0,639.3940,9.1280,634.8300,37.8625,0.0828,85.3,28.373,62.119
29996,499,5.6,23.918,55.371,5.2888,20.200,CCW,0,0.0,674.3881,9.9433,669.4165,49.0259,0.0783,85.1,26.629,61.252
29997,499,5.7,25.106,53.261,5.2888,22.628,CCW,0,0.0,704.5535,10.1316,699.4877,34.5865,0.0841,84.9,25.107,61.060
29998,499,5.8,26.493,51.351,5.2888,18.808,CCW,0,0.0,734.9189,10.4994,729.6692,30.0712,0.0860,84.7,23.546,60.694
29999,499,5.9,28.100,48.945,5.2888,24.058,CCW,0,0.0,765.6186,10.7178,760.2597,30.1815,0.0860,84.5,21.926,60.482

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   bacterium_id                  30000 non-null  int64
 1   time_s                        30000 non-null  float64
 2   x_um                          30000 non-null  float64
 3   y_um                          30000 non-null  float64
 4   heading_rad                   30000 non-null  float64
 5   speed_um_s                    30000 non-null  float64
 6   motor_state                   30000 non-null  object
 7   is_tumble                     30000 non-null  int64
 8   tumble_angle_rad              30000 non-null  float64
 9   attractant_conc_uM            30000 non-null  float64
 10  repellent_conc_uM             30000 non-null  float64
 11  net_signal                    30000 non-null  float64
 12  signal_delta                  30000 non-null  float64
 13  tumble_probability            30000 non-null  float64
 14  energy_level                  30000 non-null  float64
 15  dist_to_attractant_center_um  30000 non-null  float64
 16  dist_to_repellent_center_um   30000 non-null  float64
dtypes: float64(14), int64(2), object(1)
memory usage: 3.9+ MB

In [15]:
df.columns

Index(['bacterium_id', 'time_s', 'x_um', 'y_um', 'heading_rad', 'speed_um_s',
       'motor_state', 'is_tumble', 'tumble_angle_rad', 'attractant_conc_uM',
       'repellent_conc_uM', 'net_signal', 'signal_delta', 'tumble_probability',
       'energy_level', 'dist_to_attractant_center_um',
       'dist_to_repellent_center_um'],
      dtype='object')

In [24]:
df.size

510000

In [16]:
df.shape

(30000, 17)

In [17]:
df.isnull().sum()

bacterium_id                    0
time_s                          0
x_um                            0
y_um                            0
heading_rad                     0
speed_um_s                      0
motor_state                     0
is_tumble                       0
tumble_angle_rad                0
attractant_conc_uM              0
repellent_conc_uM               0
net_signal                      0
signal_delta                    0
tumble_probability              0
energy_level                    0
dist_to_attractant_center_um    0
dist_to_repellent_center_um     0
dtype: int64

In [18]:
df['signal_delta'].unique()

array([  0.    ,  23.4903, -20.129 , ...,  34.5865,  30.0712,  30.1815])

In [19]:
df['signal_delta'].nunique()

25913

In [20]:
df[df["signal_delta"] >5]

,bacterium_id,time_s,x_um,y_um,heading_rad,speed_um_s,motor_state,is_tumble,tumble_angle_rad,attractant_conc_uM,repellent_conc_uM,net_signal,signal_delta,tumble_probability,energy_level,dist_to_attractant_center_um,dist_to_repellent_center_um
1,0,0.1,38.418,89.097,0.9652,0.000,CW,1,2.3671,397.0274,46.9390,373.5579,23.4903,0.0889,99.1,40.777,42.566
9,0,0.9,39.709,94.604,3.5560,17.558,CCW,0,0.0000,312.1909,46.0176,289.1822,5.4426,0.0973,97.0,45.776,42.856
11,0,1.1,36.251,92.763,3.5560,19.398,CCW,0,0.0000,325.9771,37.9723,306.9909,8.6831,0.0958,96.6,44.918,45.572
12,0,1.2,33.829,92.027,3.5560,20.687,CCW,0,0.0000,324.1519,32.3682,307.9677,9.1257,0.0955,96.4,45.031,47.712
15,0,1.5,35.582,90.789,1.4823,0.000,CW,1,2.3593,353.5303,37.5926,334.7340,26.7662,0.0875,94.8,43.262,45.710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,499,5.5,22.425,56.680,5.2888,21.035,CCW,0,0.0000,639.3940,9.1280,634.8300,37.8625,0.0828,85.3,28.373,62.119
29996,499,5.6,23.918,55.371,5.2888,20.200,CCW,0,0.0000,674.3881,9.9433,669.4165,49.0259,0.0783,85.1,26.629,61.252
29997,499,5.7,25.106,53.261,5.2888,22.628,CCW,0,0.0000,704.5535,10.1316,699.4877,34.5865,0.0841,84.9,25.107,61.060
29998,499,5.8,26.493,51.351,5.2888,18.808,CCW,0,0.0000,734.9189,10.4994,729.6692,30.0712,0.0860,84.7,23.546,60.694
29999,499,5.9,28.100,48.945,5.2888,24.058,CCW,0,0.0000,765.6186,10.7178,760.2597,30.1815,0.0860,84.5,21.926,60.482

In [21]:
a=df.loc[1:4,'signal_delta']
a

1    23.4903
2     0.0000
3   -20.1290
4   -20.2919
Name: signal_delta, dtype: float64

In [22]:
df.iloc[1:10,0:5]

   bacterium_id  time_s    x_um    y_um  heading_rad
1             0     0.1  38.418  89.097       0.9652
2             0     0.2  39.333  90.475       0.9652
3             0     0.3  39.849  91.798       0.9652
4             0     0.4  40.716  93.161       0.9652
5             0     0.5  41.631  94.026       0.9652
6             0     0.6  42.629  95.511       0.9652
7             0     0.7  42.629  95.511       3.5560
8             0     0.8  40.483  94.953       3.5560
9             0     0.9  39.709  94.604       3.5560

In [23]:
dat=pd.DataFrame({
    'Name':['Yadu','Rithu', 'Elakkiya','Muth'],
    'Marks':[99,99,95, 97]
})
dat

       Name  Marks
0      Yadu     99
1     Rithu     99
2  Elakkiya     95
3      Muth     97

In [26]:
gg=df.groupby('x_um')['x_um'].mean()

In [27]:
gg

x_um
0.000        0.000
0.013        0.013
0.014        0.014
0.015        0.015
0.022        0.022
            ...
99.992      99.992
99.994      99.994
99.997      99.997
99.999      99.999
100.000    100.000
Name: x_um, Length: 21805, dtype: float64

In [28]:
g1=df.groupby('x_um')['x_um'].std()

g2=df.groupby('x_um')['x_um'].median()

g3=df.groupby('x_um')['x_um'].size()

In [29]:
g1

x_um
0.000      0.0
0.013      0.0
0.014      NaN
0.015      NaN
0.022      NaN
          ...
99.992     NaN
99.994     NaN
99.997     0.0
99.999     NaN
100.000    0.0
Name: x_um, Length: 21805, dtype: float64

In [30]:
g2

x_um
0.000        0.000
0.013        0.013
0.014        0.014
0.015        0.015
0.022        0.022
            ...
99.992      99.992
99.994      99.994
99.997      99.997
99.999      99.999
100.000    100.000
Name: x_um, Length: 21805, dtype: float64

In [31]:
g3

x_um
0.000      1207
0.013         3
0.014         1
0.015         1
0.022         1
           ...
99.992        1
99.994        1
99.997        2
99.999        1
100.000    1503
Name: x_um, Length: 21805, dtype: int64

In [36]:
da1=df.sort_values(by='x_um')
da1.head()

,bacterium_id,time_s,x_um,y_um,heading_rad,speed_um_s,motor_state,is_tumble,tumble_angle_rad,attractant_conc_uM,repellent_conc_uM,net_signal,signal_delta,tumble_probability,energy_level,dist_to_attractant_center_um,dist_to_repellent_center_um
15319,255,1.9,0.0,57.356,2.7103,21.391,CCW,0,0.0000,241.9686,0.7930,241.5721,-37.0487,0.1000,95.5,50.538,83.143
20800,346,4.0,0.0,64.565,2.5089,21.536,CCW,0,0.0000,221.6296,0.9878,221.1357,-30.4144,0.1000,90.8,52.078,81.475
10888,181,2.8,0.0,96.096,2.2884,16.575,CCW,0,0.0000,76.5833,0.9715,76.0976,-7.8754,0.1000,94.2,68.006,81.603
20814,346,5.4,0.0,73.797,5.5219,0.000,CW,1,1.4463,182.0439,1.1590,181.4644,5.2825,0.0974,87.0,55.374,80.240
26455,440,5.5,0.0,0.000,4.3255,22.012,CCW,0,0.0000,62.1765,0.0071,62.1730,0.0000,0.1000,87.8,70.711,113.137

In [35]:

import numpy as np
# Creating a sample dataframe with missing values
data = {
    'Name': ['Yadu', 'Rithu', 'Elakkiya', 'Muth'],
    'Score': [99, np.nan, 95, np.nan],
    'City': ['Chennai', 'Bangalore', np.nan, 'Chennai']
}
df_sample = pd.DataFrame(data)

# Fill all NaN values with 0
df_filled = df_sample.fillna(0)
print(df_filled)

       Name  Score       City
0      Yadu   99.0    Chennai
1     Rithu    0.0  Bangalore
2  Elakkiya   95.0          0
3      Muth    0.0    Chennai

In [34]:
da1=df.copy()
da1.insert(0,'Type','Bacteria')
da1.head()

,Type,bacterium_id,time_s,x_um,y_um,heading_rad,speed_um_s,motor_state,is_tumble,tumble_angle_rad,attractant_conc_uM,repellent_conc_uM,net_signal,signal_delta,tumble_probability,energy_level,dist_to_attractant_center_um,dist_to_repellent_center_um
0,Bacteria,0,0.0,38.418,89.097,4.5993,19.532,CCW,0,0.0000,397.0274,46.9390,373.5579,0.0000,0.1000,99.8,40.777,42.566
1,Bacteria,0,0.1,38.418,89.097,0.9652,0.000,CW,1,2.3671,397.0274,46.9390,373.5579,23.4903,0.0889,99.1,40.777,42.566
2,Bacteria,0,0.2,39.333,90.475,0.9652,18.838,CCW,0,0.0000,377.8229,48.7878,353.4289,0.0000,0.1000,98.9,41.857,41.995
3,Bacteria,0,0.3,39.849,91.798,0.9652,18.152,CCW,0,0.0000,357.7704,49.2668,333.1370,-20.1290,0.1000,98.7,43.013,41.849
4,Bacteria,0,0.4,40.716,93.161,0.9652,19.144,CCW,0,0.0000,338.6360,50.6601,313.3059,-20.2919,0.1000,98.5,44.149,41.430

In [32]:
data=df.drop(columns={'bacterium_id'})
data

,time_s,x_um,y_um,heading_rad,speed_um_s,motor_state,is_tumble,tumble_angle_rad,attractant_conc_uM,repellent_conc_uM,net_signal,signal_delta,tumble_probability,energy_level,dist_to_attractant_center_um,dist_to_repellent_center_um
0,0.0,38.418,89.097,4.5993,19.532,CCW,0,0.0000,397.0274,46.9390,373.5579,0.0000,0.1000,99.8,40.777,42.566
1,0.1,38.418,89.097,0.9652,0.000,CW,1,2.3671,397.0274,46.9390,373.5579,23.4903,0.0889,99.1,40.777,42.566
2,0.2,39.333,90.475,0.9652,18.838,CCW,0,0.0000,377.8229,48.7878,353.4289,0.0000,0.1000,98.9,41.857,41.995
3,0.3,39.849,91.798,0.9652,18.152,CCW,0,0.0000,357.7704,49.2668,333.1370,-20.1290,0.1000,98.7,43.013,41.849
4,0.4,40.716,93.161,0.9652,19.144,CCW,0,0.0000,338.6360,50.6601,313.3059,-20.2919,0.1000,98.5,44.149,41.430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,5.5,22.425,56.680,5.2888,21.035,CCW,0,0.0000,639.3940,9.1280,634.8300,37.8625,0.0828,85.3,28.373,62.119
29996,5.6,23.918,55.371,5.2888,20.200,CCW,0,0.0000,674.3881,9.9433,669.4165,49.0259,0.0783,85.1,26.629,61.252
29997,5.7,25.106,53.261,5.2888,22.628,CCW,0,0.0000,704.5535,10.1316,699.4877,34.5865,0.0841,84.9,25.107,61.060
29998,5.8,26.493,51.351,5.2888,18.808,CCW,0,0.0000,734.9189,10.4994,729.6692,30.0712,0.0860,84.7,23.546,60.694
29999,5.9,28.100,48.945,5.2888,24.058,CCW,0,0.0000,765.6186,10.7178,760.2597,30.1815,0.0860,84.5,21.926,60.482

In [39]:
'''using insert in a sample dataframe'''
# Sample DataFrame
df = pd.DataFrame({
    'Name': ['Yadu', 'Rithu', 'Muth'],
    'Score': [99, 95, 97]
})

# Insert 'City' at index 1 (between Name and Score)
df.insert(1, 'City', ['Chennai', 'Bangalore', 'Chennai'])
print(df)

    Name       City  Score
0   Yadu    Chennai     99
1  Rithu  Bangalore     95
2   Muth    Chennai     97

In [40]:
'''using delete in a sample dataframe'''
# Delete the 'City' column
df_dropped = df.drop('City', axis=1)

# Delete the first row (index 0)
df_no_row = df.drop(0, axis=0)

print(df_dropped)

    Name  Score
0   Yadu     99
1  Rithu     95
2   Muth     97

In [41]:
'''using assign'''
# Create a 'Passed' column based on Score
df_new = df.assign(Passed = df['Score'] > 90)
print(df_new)

    Name       City  Score  Passed
0   Yadu    Chennai     99    True
1  Rithu  Bangalore     95    True
2   Muth    Chennai     97    True

In [42]:
'''using replace'''
# Replace 'Chennai' with 'Madras'
df_replaced = df.replace('Chennai', 'Madras')

# Replace multiple values using a dictionary
df_cleaned = df.replace({99: 100, 'Bangalore': 'Bengaluru'})
print(df_cleaned)

    Name       City  Score
0   Yadu    Chennai    100
1  Rithu  Bengaluru     95
2   Muth    Chennai     97